---
name: "AnimatedCovers"
guid: "eb5d7894-8eef-4b36-aa6f-5d124e828ce1"
version: "1.0.0.0"
targetAbi: "10.9.0"
framework: "net8.0"
overview: "Provides animated covers for your movies"
description: >
  Allows you to generate animated WebP covers for your movie
  libraries and configure them.
category: "Metatada"
owner: "shirkit"
artifacts:
- "AnimatedCovers.dll"
changelog: >
  changelog
